#!/bin/bash

source service_host.sh

if (( $# == 3  ));
then
        server=`eval echo \\$$1`
        scp root@${server}:$2 $3
else
        echo "usage:copyfrom server_name server_file localfile"
fi

