#!/bin/bash

heaven="heaven.com"
t0="192.168.2.21"
t1="192.168.2.13"
t2="192.168.2.15"
t3="192.168.2.9"
t4="192.168.2.20"
t5="192.168.2.10"
e0="192.168.2.41"


if (( $# == 2  ));
then
	if [[ $1 == *"local"* ]];
        then
                server=`eval echo \\$$1`
                ssh mtty@${server} "${2}"
	elif [[ $1 != *"mysql"* ]];
	then
		server=`eval echo \\$$1`
		ssh root@${server} "${2}"
	fi
else
	echo "usage:remoteexec server_name command"
fi

